export const EventTypes = {
  SHIFT_OPEN: 'SHIFT_OPEN',
  SHIFT_CLOSING: 'SHIFT_CLOSING',
  SHIFT_CLOSED: 'SHIFT_CLOSED',
  
  SERVICE_ADDED: 'SERVICE_ADDED',
  PRODUCT_SOLD: 'PRODUCT_SOLD',
  EXPENSE_ADDED: 'EXPENSE_ADDED',
  
  // أحداث الفواتير والعملاء (جديدة)
  INVOICE_CREATED: 'INVOICE_CREATED',
  CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED'
};
